Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccess.EntityFramework;
using DataAccess;
namespace Magazine.Controllers
{
    public class HomePageController : Controller
    {
        // GET: HomePage
        public ActionResult Index(string searchst)
        {
            var iplArticles = new ArticleModel();
            var model = iplArticles.listAllArticles();
            if (searchst == null) { return View(model); } else
            {
                List<article> model1 = model.Where(s => s.title.Contains(searchst)).ToList(); //lọc theo chuỗi tìm kiếm                     
                return View(model1);
            }
            
        }
        public ActionResult Search(string m)
        {
            var iplArticles = new ArticleModel();
            var model = iplArticles.listFoundArticles(m);
            return View(model);
        }
        [HttpPost]
        public ActionResult Search1(string m)
        {
            var iplArticles = new ArticleModel();
            var model = iplArticles.listFoundArticles(m);
            return View(model);
        }
        public ActionResult Test()
        {
            return View(new article());
        }

        // GET: HomePage/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HomePage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HomePage/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HomePage/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HomePage/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: HomePage/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HomePage/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Detail(int id)
        {

            var impArticle = new ArticleModel();
            var modell = impArticle.getByID(id);
            return View(modell);
        }
    }
}

Views/HomePage/Detail.cshtml
@model DataAccess.EntityFramework.article

@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}

@section ClientScript1{
    <script type="text/javascript">
        $(document).ready(function () {
            $(document).mouseup(function (e) {
                var container = $(".top-bar__search");

                if (!container.is(e.target) && container.has(e.target).length === 0) {
                    container.hide();
                }
            });


            window.onload = function () {
                $('.content-post__img').slick({
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    dots: true,
                    // centerMode: true,
                    // focusOnSelect: true,
                    arrows: true,
                    infinite: true,
                    // speed: 300,
                    slidesToShow: 1,
                    adaptiveHeight: true,
                    autoplay: true,
                    autoplaySpeed: 2000,
                });
            };

        });
    </script>
    }


<div class="mc-post">
    <div class="mcp__large-post">
        <div>
            <div class="mcp__lp-title">
                <div class="lp-date">
                    <div>@(Model.create_time.HasValue?Model.create_time.Value.ToString("dd") : "")</div>
                    <span>@(Model.create_time.HasValue?Model.create_time.Value.ToString("MM") : "")</span>
                </div>
                <div class="lp-title">
                    <div>
                        <span>by</span>
                        <span>Pham Thanh</span>
                        <span>/</span>
                        <span>Breaking news</span>
                    </div>
                    <a href="single-post1.html">
                        <div>
                            @Html.Raw(Model.title)
                        </div>
                    </a>

                    <div class="post-wishh">
                        <i class="fas fa-heart"></i>
                    </div>
                </div>

            </div>
            <div class="content-post">
                @Html.Raw(Model.textbody)
            </div>

            <div class="tag-share">
                <div class="ts-tag">
                    <span>Tag:</span>
                    <div>Thinkpad</div>
                    <div>Videos</div>
                    <div>Reviews</div>
                </div>
                <div class="ts-share">
                    <span>Share:</span>
                    <i class="fab fa-facebook-f"><a href=""></a></i>
                    <i class="fab fa-twitter"><a href=""></a></i>
                    <i class="fab fa-instagram"><a href=""></a></i>
                    <i class="fab fa-youtube"><a href=""></a></i>
                </div>
            </div>

            <div class="p-n">
                <a href="" class="pn-pre">
                    <i class="fas fa-chevron-left"></i>
                    <span>PREV POSTS</span>
                </a>
                <a href="" class="pn-next">
                    <span>NEXT POSTS</span>
                    <i class="fas fa-chevron-right"></i>
                </a>
            </div>

            <div class="comments">
                <div>Leave a comment</div>
                <form action="">
                    <div class="list-input-sp">
                        <input type="text" name="" id="" placeholder="Name">
                        <input type="text" name="" id="" placeholder="Email">
                        <input type="text" name="" id="" placeholder="Website">
                    </div>
                    <textarea name="" id="txt-cmt" placeholder="Comment"></textarea>
                    <div class="btn-sb-cmtt">
                        <input id="btn-sb-cmt" type="submit" value="SUBMIT COMMENT">
                    </div>
                </form>
            </div>

        </div>
    </div>


</div>

Views/HomePage/Index.cshtml
@model IEnumerable<DataAccess.EntityFramework.article>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}


<div class="mc-post">
    <div class="list-normal-post">
        @foreach (var item in Model)
        {

            <div class="mp">
                <div class="mp-img">
                    <img src="@Html.DisplayFor(modelItem => item.image)" alt="">
                    <div class="post-wish1">
                        <i class="fas fa-heart"></i>
                    </div>
                </div>
                <div class="mp-title">
                    <div style="position: relative; z-index: 10;">
                        <div class="lp-date">
                            <div>@(item.create_time.HasValue?item.create_time.Value.ToString("dd") : "")</div>
                            <span>@(item.create_time.HasValue?item.create_time.Value.ToString("MM") : "")</span>
                        </div>
                        <div class="mp-nav">
                            <span>by</span>
                            <span>Pham Thanh</span>
                            <span>/</span>
                            <span>Breaking news</span>
                        </div>
                    </div>
                    <div>
                        <a href="@Url.Action("Detail", "HomePage" , new {id = item.article_id})">
                            <span>@Html.Raw(item.title)</span>
                        </a>
                    </div>
                    <div class="pretext" style="">                       
                        @Html.Raw(item.textbody)
                    </div>
                </div>
            </div>

        }
    </div>

    <div class="page-number">
        <div>
            <div style="background-color: white;"><a style="color: black; text-decoration: none;" href="blog2.html">1</a></div>
            <div style="background-color: black; color: white;">2</div>
            <div>3</div>
            <div><i class="fal fa-chevron-right"></i></div>
        </div>
    </div>

</div>

Views/HomePage/Search.cshtml
@model IEnumerable<DataAccess.EntityFramework.article>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout2.cshtml";
}



<div class="mc-post">
    <div class="list-normal-post">
        @foreach (var item in Model)
        {

            <div class="mp">
                <div class="mp-img">
                    <img src="@Html.DisplayFor(modelItem => item.image)" alt="">
                    <div class="post-wish1">
                        <i class="fas fa-heart"></i>
                    </div>
                </div>
                <div class="mp-title">
                    <div style="position: relative; z-index: 10;">
                        <div class="lp-date">
                            <div>@Html.DisplayFor(modelItem => item.create_time)</div>
                            <span>@Html.DisplayFor(modelItem => item.create_time)</span>
                        </div>
                        <div class="mp-nav">
                            <span>by</span>
                            <span>Pham Thanh</span>
                            <span>/</span>
                            <span>Breaking news</span>
                        </div>
                    </div>
                    <div>
                        <a href="">
                            @Html.DisplayFor(modelItem => item.title)
                        </a>
                    </div>
                    <div style="max-height: 50px; overflow: hidden">
                        @Html.DisplayFor(modelItem => item.textbody)
                    </div>
                </div>
            </div>

        }
    </div>

    <div class="page-number">
        <div>
            <div style="background-color: white;"><a style="color: black; text-decoration: none;" href="blog2.html">1</a></div>
            <div style="background-color: black; color: white;">2</div>
            <div>3</div>
            <div><i class="fal fa-chevron-right"></i></div>
        </div>
    </div>

</div>